Update package.json
revert revision date picker, because of this error in build src:

liferay-amd-loader |
A require() call success handler has thrown an error.
Note that even if the call stack of this error trace looks like coming from the Liferay AMD Loader, it is not an error in the Loader what has caused it, but an error in the handler's code.
The reason why the Loader is in the stack trace is because it is printing the error on behalf of the handler so that it doesn't get lost.
However, we recommend wrapping all handler code inside a try/catch to be able to recover from errors better and to avoid the appearance of this message.

TypeError: _shared.useInternalState is not a function